pub mod agent_tool;
pub mod agents;
pub mod ask_user;
pub mod bash;
pub mod bash_security;
pub mod brief_tool;
pub mod config_tool;
pub mod cron_tool;
pub mod ctx_inspect_tool;
pub mod edit;
pub mod glob_tool;
pub mod grep;
pub mod list_peers_tool;
pub mod lsp_tool;
pub mod mcp_auth_tool;
pub mod mcp_resource_tools;
pub mod mcp_tool;
pub mod monitor_tool;
pub mod notebook_edit;
pub mod plan_mode;
pub mod powershell;
pub mod push_notification_tool;
pub mod read;
pub mod registry;
pub mod remote_trigger;
pub mod repl_tool;
pub mod send_message;
pub mod send_user_file_tool;
pub mod skill_tool;
pub mod sleep_tool;
pub mod snip_tool;
pub mod subscribe_pr_tool;
pub mod suggest_background_pr_tool;
pub mod synthetic_output;
pub mod task_tools;
pub mod team_tools;
pub mod terminal_capture_tool;
pub mod todo_write;
pub mod tool_search;
pub mod verify_plan_tool;
pub mod web_browser_tool;
pub mod web_fetch;
pub mod web_search;
pub mod workflow_tool;
pub mod worktree_tools;
pub mod write;

pub use mcp_tool::register_mcp_tools;
pub use registry::{ProgressSender, ReadFileState, ToolExecutor, ToolRegistry, ToolUseContext};

use std::sync::Arc;

pub fn build_default_registry() -> ToolRegistry {
    let mut reg = ToolRegistry::new();
    reg.register(Arc::new(bash::BashTool::new()));
    reg.register(Arc::new(read::FileReadTool));
    reg.register(Arc::new(write::FileWriteTool));
    reg.register(Arc::new(edit::FileEditTool));
    reg.register(Arc::new(grep::GrepTool));
    reg.register(Arc::new(glob_tool::GlobTool));
    reg.register(Arc::new(web_fetch::WebFetchTool));
    // WebSearchTool is a server-side tool (handled by the API, not client-side).
    // It is NOT registered here. Its definition is injected into the API request.
    reg.register(Arc::new(task_tools::TaskCreateTool));
    reg.register(Arc::new(task_tools::TaskListTool));
    reg.register(Arc::new(task_tools::TaskUpdateTool));
    reg.register(Arc::new(task_tools::TaskGetTool));
    reg.register(Arc::new(task_tools::TaskStopTool));
    reg.register(Arc::new(task_tools::TaskOutputTool));
    reg.register(Arc::new(notebook_edit::NotebookEditTool));
    reg.register(Arc::new(agent_tool::AgentTool));
    reg.register(Arc::new(config_tool::ConfigTool::default()));
    reg.register(Arc::new(plan_mode::EnterPlanModeTool));
    reg.register(Arc::new(plan_mode::ExitPlanModeTool));
    reg.register(Arc::new(ask_user::AskUserQuestionTool));
    reg.register(Arc::new(brief_tool::BriefTool));
    reg.register(Arc::new(send_message::SendMessageTool));
    reg.register(Arc::new(lsp_tool::LSPTool));
    reg.register(Arc::new(tool_search::ToolSearchTool));
    reg.register(Arc::new(team_tools::TeamCreateTool));
    reg.register(Arc::new(team_tools::TeamDeleteTool));
    reg.register(Arc::new(remote_trigger::RemoteTriggerTool));
    reg.register(Arc::new(worktree_tools::EnterWorktreeTool));
    reg.register(Arc::new(worktree_tools::ExitWorktreeTool));
    reg.register(Arc::new(mcp_resource_tools::ListMcpResourcesTool));
    reg.register(Arc::new(mcp_resource_tools::ReadMcpResourceTool));
    reg.register(Arc::new(powershell::PowerShellTool));
    reg.register(Arc::new(cron_tool::ScheduleCronTool));
    reg.register(Arc::new(skill_tool::SkillTool));
    reg.register(Arc::new(sleep_tool::SleepTool));
    reg.register(Arc::new(synthetic_output::SyntheticOutputTool));
    reg.register(Arc::new(todo_write::TodoWriteTool));
    reg.register(Arc::new(mcp_auth_tool::McpAuthTool));
    reg.register(Arc::new(repl_tool::REPLTool));
    reg.register(Arc::new(monitor_tool::MonitorTool));
    reg.register(Arc::new(push_notification_tool::PushNotificationTool));
    reg.register(Arc::new(send_user_file_tool::SendUserFileTool));
    reg.register(Arc::new(terminal_capture_tool::TerminalCaptureTool));
    reg.register(Arc::new(ctx_inspect_tool::CtxInspectTool));
    reg.register(Arc::new(snip_tool::SnipTool));
    reg.register(Arc::new(web_browser_tool::WebBrowserTool));
    reg.register(Arc::new(verify_plan_tool::VerifyPlanExecutionTool));
    reg.register(Arc::new(subscribe_pr_tool::SubscribePRTool));
    reg.register(Arc::new(
        suggest_background_pr_tool::SuggestBackgroundPRTool,
    ));
    reg.register(Arc::new(list_peers_tool::ListPeersTool));
    reg.register(Arc::new(workflow_tool::WorkflowTool));
    reg.register(Arc::new(cron_tool::CronDeleteTool));
    reg.register(Arc::new(cron_tool::CronListTool));
    reg
}
